### ISSUE TITLE
Could we consider other locales for chrono parsing ?

### ISSUE THREAD

**Issue by Geslain** [mtimkovich/rip_quick_add#2]
Hello !

First of all, thank you for your job and maintaining it, your chrome extension is exactly what i was looking for.

But sadly it doesn't work for other locales than english, because your only using chrono's default one. Could you consider adding support for all chrono supported locales ? I would be glad to submit you a pull request with the changes if you're ok !

**Comment by mtimkovich** [comment]
I'm glad you like it! That would be a good addition. I don't see a straightforward way to do that. Maybe loop through all the locales and see which ones successfully parse? I'd certainly accept a PR for it!

Edit: Or maybe you're suggesting adding an option for which locale to parse for? That could work better.

**Comment by Geslain** [comment]
> Maybe loop through all the locals and see which ones successfully parse

That was my first thought, but actually I stumbled on case that changed my mind:

I'm French so I wanted the following date to be parsed in my language

`07:30 vendredi 12 juillet, 2024 - 09:20 vendredi 12 juillet, 2024`

Which correspond to `7:30AM Friday July 12th - 9:20AM Friday July 12th` in English 

Problem is, this is actually parsed by [chrono](https://github.com/wanasit/chrono) because it detects time. So the JavaScript DateTime object that results from parsing is basically today's date but with respectively time at 7:30am and 9:20am. So we can't just loop on locales like we were thinking.

So I came with another idea which is the one you're talking about in your edit: let the user chose the language he wants to use. I made a prototype just to see I it would work, these are screenshots of a basic example:

* For popup

<img width="280" alt="image" src="https://github.com/mtimkovich/rip_quick_add/assets/6905412/bc8830e3-3f9a-4d88-985c-012b8293d5db">
 
* For context menu
 
<img width="443" alt="image" src="https://github.com/mtimkovich/rip_quick_add/assets/6905412/8d5ef172-9b7d-4eac-9953-c69f93b64923">
 
 
This is a simple example but maybe instead of allowing user to select language in popup or context menu we should add a config page for the extension ? What are your thoughts ?
 
 
If you want to take a look at my example, i forked your project and made a "wip" [pull request](https://github.com/Geslain/rip_quick_add/pull/1) or else look at the [custom-chrome-extension](https://github.com/Geslain/rip_quick_add/tree/custom-chrome-extension) branch. For development convenience i transformed you server baser architecture into a rollup base architecture to embed all code and avoid API calls, but as you're using this code also on your website maybe you want to keep it that way.

**Comment by mtimkovich** [comment]
That's a great point. The wip looks good. It would be best to create an options page and set the language there.

**Comment by Geslain** [comment]
I agree, I'll look into it and make a pull request. Are you interested by the rollup approach or would you like to keep it that way ?

**Comment by mtimkovich** [comment]
I like the roll up approach, let's do that. 👍

**Comment by Geslain** [comment]
Oh didn't saw your answer. I just pushed a pull request with your current approach
I'll make a second one with new approach
